version: '1.0.{build}'
clone_folder: c:\projects\angular4
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  nodejs_version: "6"
  DOCKER_USER:
    secure: 8daLcI/7NXoVsfiymJHpiw==
  DOCKER_PASS:
    secure: XnYt56leSB7q76Ou5TEoXQ==

cache:
  - node_modules
  - '%APPDATA%\npm-cache'              # npm cache

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: npm install -g npm@3
  
build_script:  
  - ps: npm i
  - ps: npm run clean
  - ps: npm run build

before_test:
  - ps: npm run test
test_script:
  - node --version
  - npm --version

deploy_script:  
 - cd C:\projects\angular4
 - ps: docker build -f Dockerfile -t "angularvn/angular4-seed:nanoserver-$env:APPVEYOR_BUILD_NUMBER" .
 - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
 - ps: docker push "angularvn/angular4-seed:nanoserver-$env:APPVEYOR_BUILD_NUMBER"

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

