version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/
    environment:
      - NG2ENV : "Prod"
    steps:
      - checkout
      - run:
          name: Install curl and git
          command: |
            apt update
            apt install -y curl git
      - setup_remote_docker
      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install NodeJS v8
          command: |
            curl -sL https://deb.nodesource.com/setup_8.x | bash -
            apt update
            apt install -y nodejs
      - run:
          name: Build and bundle from source
          command: |
            if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
            npm i
            npm run rebuild
      - run:
          name: Build and push Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -f Dockerfile -t angularvn/angular4-seed .
          # docker login -u $DOCKER_USER -p $DOCKER_PASS
          # docker push angularvn/angular4-seed
          # docker build -f docker/runtime.dockerfile -t angularvn/angular4-seed:$TAG .
          # docker push angularvn/angular4-seed:$TAG
      - save_cache:
          key: angular4-seed-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.caches
            - ~/.npm
